version: '2'

services:
  application:
    image: debian
    volumes:
      - ./:/var/www/app
  workspace:
    image: dung13890/laravel-env:latest
    restart: always
    volumes_from:
      - application
    tty: true
    links:
      - mariadb
      - mariadb_test
      - nginx:hang.localhost
  mariadb:
    restart: always
    image: mariadb:latest
    volumes:
      - ./.docker/mariadb:/var/lib/mysql
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
  mariadb_test:
    restart: always
    image: mariadb:latest
    volumes:
      - ./.docker/mariadb_test:/var/lib/mysql
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: homestead_test
      MYSQL_USER: homestead_test
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8000:8080
  redis:
      restart: always
      image: redis:latest
      expose:
        - "6379"
      volumes:
        - ./.docker/redis:/data
  nginx:
    image: dung13890/nginx-env
    restart: always
    volumes_from:
      - application
    ports:
      - "80:80"
      - "443:443"
    tty: true
    command: /bin/bash -c "/serve.sh workspace hang.localhost /var/www/app/public && nginx"
  node:
    image: dung13890/vue-env
    environment:
      - NODE_ENV=development
    restart: always
    volumes:
      - ./.documents/api:/var/www/app
    tty: true
    ports:
      - "4000:4000"
